"""Guard against breaching Discord's 25-static-choices-per-option cap.

Discord rejects any slash-command option carrying more than 25 static
``choices`` with API error 50035. py-cord registers every command in a single
all-or-nothing bulk PUT on ``on_connect``, so a SINGLE over-limit choices list
silently aborts slash-command registration for EVERY cog in the bot -- the most
catastrophic silent failure in this family of bots.

This test discovers every module-level ``*_CHOICES`` list at import time and
asserts each stays within the cap. It is intentionally generic: any future
choices list (including ones generated by a comprehension and resolved at module
load) is covered automatically as long as it follows the ``*_CHOICES`` naming
convention and lives in the modules enumerated below.
"""

from __future__ import annotations

import importlib

import pytest

pytest.importorskip("discord")

# Discord's hard cap on static choices for a single slash-command option.
DISCORD_MAX_STATIC_CHOICES = 25

# Modules that define slash-command static choices. discord-openrouter keeps all
# of them in command_options.py; model/voice menus are built dynamically from
# OpenRouter's /v1/models endpoint, so there are no static model choice lists.
CHOICE_MODULES = (
    "discord_openrouter.cogs.openrouter.command_options",
)


def _discover_choice_lists() -> list[tuple[str, str, list]]:
    """Return (module, name, list) for every module-level ``*_CHOICES`` list.

    Counts the already-RESOLVED module-level objects, so comprehension-generated
    lists are measured at their real runtime length with zero AST machinery.
    """
    found: list[tuple[str, str, list]] = []
    for module_name in CHOICE_MODULES:
        module = importlib.import_module(module_name)
        for attr in dir(module):
            if not attr.endswith("_CHOICES"):
                continue
            value = getattr(module, attr)
            if isinstance(value, list):
                found.append((module_name, attr, value))
    return found


_CHOICE_LISTS = _discover_choice_lists()


def test_choice_lists_were_discovered() -> None:
    """Fail loudly if the discovery wiring stops finding any choices lists.

    Without this, a refactor that renames the module or the ``*_CHOICES``
    convention would make the parametrized guard below silently collect zero
    cases and pass vacuously -- re-introducing the exact silent failure we guard.
    """
    assert _CHOICE_LISTS, (
        "No *_CHOICES lists were discovered in "
        f"{CHOICE_MODULES!r}. The 25-choice guard is now vacuous; update "
        "CHOICE_MODULES / the discovery convention in this test."
    )


@pytest.mark.parametrize(
    ("module_name", "list_name", "choices"),
    _CHOICE_LISTS,
    ids=[f"{name}" for _, name, _ in _CHOICE_LISTS],
)
def test_choice_list_within_discord_cap(
    module_name: str, list_name: str, choices: list
) -> None:
    count = len(choices)
    assert count <= DISCORD_MAX_STATIC_CHOICES, (
        f"{module_name}.{list_name} has {count} choices, exceeding Discord's "
        f"limit of {DISCORD_MAX_STATIC_CHOICES} static choices per slash-command "
        "option. Discord will reject the bulk command sync with API error 50035, "
        "silently aborting slash-command registration for EVERY cog in the bot. "
        "Trim the list to <= 25 or switch the option to an autocomplete handler."
    )
